# You must change these to your own details.
[package]
name = "client"
description = "client"
version = "0.1.0"
authors = ["bakape <bakape@gmail.com>"]
categories = ["wasm"]
readme = "README.md"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.54"
brunhild = {git = "https://github.com/bakape/brunhild.git"}
protocol = { path = "../protocol" }

[dependencies.web-sys]
version = "0.3.31"
features = [
  'Document',
  'Window',
  'HtmlElement',
  'Element',
  'Node',
  "console",
  "CloseEvent",
  "ErrorEvent",
  "MessageEvent",
  "WebSocket",
  "Location",
  "Navigator",
  "EventTarget",
  "AddEventListenerOptions",
  "Event",
]

[target."cfg(debug_assertions)".dependencies]
console_error_panic_hook = "0.1.5"

[dev-dependencies]
wasm-bindgen-test = "0.3.4"
futures = "0.3.1"
js-sys = "0.3.31"
wasm-bindgen-futures = "0.4.4"
